name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      version-tag: "v17.2"
      release-version: "${{ env.version-tag }}.${{ env.GITHUB_RUN_NUMBER }}"

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag robkaandorp/rbd:${{ env.version-tag }} --tag robkaandorp/rbd:${{ env.release-version }}
    - name: Export image
      run: |
        id=$(docker create robkaandorp/rbd:${{ env.version-tag }} true)
        mkdir -p plugin/rootfs
        cp config.json plugin/
        docker export "$id" | sudo tar -x -C plugin/rootfs
        docker rm -vf "$id"
        docker rmi robkaandorp/rbd:${{ env.version-tag }}
    - name: Create tar archive
      run: tar -cf docker-volume-rbd-${{ env.release-version }}.tgz plugin/
    - name: GitHub release
      run: |
        echo ${{ github.token }} | gh auth login --with-token
        gh release create ${{ env.release-version }} *.tgz
